from __future__ import annotations

from structured_log_manager import FunnelStep


def build_alt_entry_steps(
    *,
    entry_signal: bool,
    bullish: bool,
    trend_follow_entry: bool,
    signal_is_strong: bool,
    gap_pct: float,
    min_gap_pct: float,
    htf_bullish: bool,
    volume_filter_passed: bool,
    volume_ratio: float | None,
    effective_min_volume_ratio: float,
    volatility_filter_passed: bool,
    avg_abs_change_pct: float | None,
    min_volatility_pct: float,
    max_volatility_pct: float,
    in_cooldown: bool,
    seconds_since_last_trade: float,
    can_average_down: bool,
    last_close: float,
    avg_entry_price: float | None,
    current_entry_count: int,
    max_entry_count: int,
    daily_loss_limit_reached: bool,
    daily_realized_pnl_quote: float,
    max_daily_loss_quote: float,
    order_value_quote: float,
    min_buy_order_value: float,
):
    return [
        FunnelStep(
            stage="trend",
            passed=entry_signal,
            reason="no_entry_signal",
            actual={"bullish_signal": bullish, "trend_follow_entry": trend_follow_entry},
            required={"bullish_or_trend_follow_entry": True},
        ),
        FunnelStep(
            stage="distance",
            passed=signal_is_strong,
            reason="distance_too_small",
            actual={"gap_pct": gap_pct},
            required={"min_gap_pct": min_gap_pct},
        ),
        FunnelStep(
            stage="higher_timeframe",
            passed=htf_bullish,
            reason="higher_timeframe_not_bullish",
            actual={"htf_bullish": htf_bullish},
            required={"htf_bullish": True},
        ),
        FunnelStep(
            stage="volume",
            passed=volume_filter_passed,
            reason="volume_low",
            actual={"volume_ratio": volume_ratio},
            required={"min_volume_ratio": effective_min_volume_ratio},
        ),
        FunnelStep(
            stage="volatility",
            passed=volatility_filter_passed,
            reason="volatility_out_of_range",
            actual={"avg_abs_change_pct": avg_abs_change_pct},
            required={
                "min_volatility_pct": min_volatility_pct,
                "max_volatility_pct": max_volatility_pct,
            },
        ),
        FunnelStep(
            stage="cooldown",
            passed=not in_cooldown,
            reason="cooldown_active",
            actual={"seconds_since_last_trade": seconds_since_last_trade},
            required={"cooldown_inactive": True},
        ),
        FunnelStep(
            stage="position_rule",
            passed=can_average_down,
            reason="avg_price_rule_block",
            actual={"last_close": last_close, "avg_entry_price": avg_entry_price},
            required={"required_price_lte": avg_entry_price},
        ),
        FunnelStep(
            stage="entry_limit",
            passed=current_entry_count < max_entry_count,
            reason="max_entry_reached",
            actual={"entry_count": current_entry_count},
            required={"max_entry_count": max_entry_count},
        ),
        FunnelStep(
            stage="risk_limit",
            passed=not daily_loss_limit_reached,
            reason="daily_loss_limit_reached",
            actual={"daily_realized_pnl_quote": daily_realized_pnl_quote},
            required={"min_daily_realized_pnl_quote": -max_daily_loss_quote},
        ),
        FunnelStep(
            stage="order_value",
            passed=order_value_quote > min_buy_order_value,
            reason="order_value_too_small",
            actual={"order_value_quote": order_value_quote},
            required={"min_buy_order_value": min_buy_order_value},
        ),
    ]


def build_alt_exit_steps(
    *,
    has_position: bool,
    stop_loss_triggered: bool,
    profit_protect_triggered: bool,
    break_even_guard_triggered: bool,
    bearish: bool,
    in_cooldown: bool,
    seconds_since_last_trade: float,
    signal_is_strong: bool,
    gap_pct: float,
    min_gap_pct: float,
    htf_bearish: bool,
    take_profit_ready: bool,
    pnl_pct: float | None,
    current_net_realized_pnl_pct: float | None,
    mfe_pct: float | None,
    min_take_profit_pct: float,
    fee_protect_min_net_pnl_pct: float,
    break_even_guard_min_mfe_pct: float,
    break_even_guard_floor_net_pnl_pct: float,
):
    return [
        FunnelStep(
            stage="position",
            passed=has_position,
            reason="no_position",
            actual={"has_position": has_position},
            required={"has_position": True},
        ),
        FunnelStep(
            stage="exit_trigger",
            passed=(stop_loss_triggered or profit_protect_triggered or break_even_guard_triggered or bearish),
            reason="no_exit_signal",
            actual={
                "stop_loss_triggered": stop_loss_triggered,
                "profit_protect_triggered": profit_protect_triggered,
                "break_even_guard_triggered": break_even_guard_triggered,
                "bearish_signal": bearish,
            },
            required={"exit_signal": True},
        ),
        FunnelStep(
            stage="cooldown",
            passed=(stop_loss_triggered or profit_protect_triggered or break_even_guard_triggered or not in_cooldown),
            reason="cooldown_active",
            actual={"seconds_since_last_trade": seconds_since_last_trade},
            required={"cooldown_inactive": True},
        ),
        FunnelStep(
            stage="distance",
            passed=(stop_loss_triggered or profit_protect_triggered or break_even_guard_triggered or signal_is_strong),
            reason="distance_too_small",
            actual={"gap_pct": gap_pct},
            required={"min_gap_pct": min_gap_pct},
        ),
        FunnelStep(
            stage="higher_timeframe",
            passed=(stop_loss_triggered or profit_protect_triggered or break_even_guard_triggered or htf_bearish),
            reason="higher_timeframe_not_bearish",
            actual={"htf_bearish": htf_bearish},
            required={"htf_bearish": True},
        ),
        FunnelStep(
            stage="take_profit",
            passed=(stop_loss_triggered or profit_protect_triggered or break_even_guard_triggered or take_profit_ready),
            reason="take_profit_not_reached",
            actual={
                "pnl_pct": pnl_pct,
                "net_pnl_pct_estimate": current_net_realized_pnl_pct,
                "mfe_pct": mfe_pct,
            },
            required={
                "min_take_profit_pct": min_take_profit_pct,
                "fee_protect_min_net_pnl_pct": fee_protect_min_net_pnl_pct,
                "break_even_guard_min_mfe_pct": break_even_guard_min_mfe_pct,
                "break_even_guard_floor_net_pnl_pct": break_even_guard_floor_net_pnl_pct,
            },
        ),
    ]
