"""
수정 요약
- 2026-04-03: structured TOML nested table 세트를 runtime.local.toml 로 그대로 반영하도록 저장 로직을 확장
- 전략 세트 canonical 경로를 env_overrides 에서 config/sets TOML 로 승격하고, 현재 적용은 config/runtime.local.toml 에 반영하도록 리팩터링
- conservative, medium, mixed 세트 별칭과 직접 TOML 파일 지정 방식을 모두 지원
- dry-run 으로 변경될 section/key 를 먼저 확인할 수 있게 구성

전략 세트 적용 도구

- 목적: config/sets/*.toml 세트를 현재 config/runtime.local.toml 에 반영한다.
- 입력: 세트 이름 또는 TOML 파일 경로
- 출력: 변경될 section/key 목록과 반영 결과
"""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path
from typing import Any
import re


ROOT_DIR = Path(__file__).resolve().parent.parent
TARGET_PATH = ROOT_DIR / "config" / "runtime.local.toml"
SET_DIR = ROOT_DIR / "config" / "sets"
LEGACY_SET_DIR = ROOT_DIR / "env_overrides"

SET_ALIASES = {
    "conservative": "conservative.toml",
    "medium": "medium.toml",
    "mixed": "mixed.toml",
}


def resolve_set_path(name_or_path: str) -> Path:
    """세트 별칭 또는 파일 경로를 실제 Path 로 바꾼다."""
    candidate = SET_DIR / SET_ALIASES.get(name_or_path, name_or_path)
    if candidate.exists():
        return candidate
    legacy_candidate = LEGACY_SET_DIR / name_or_path
    if legacy_candidate.exists():
        return legacy_candidate
    direct = Path(name_or_path)
    if direct.exists():
        return direct
    raise FileNotFoundError(f"세트 파일을 찾지 못했습니다: {name_or_path}")


def parse_set_file(path: Path) -> dict[str, dict[str, object]]:
    """TOML 또는 legacy env partial 파일을 section dict 로 읽는다."""
    if path.suffix.lower() == ".toml":
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            return {}
        result: dict[str, dict[str, object]] = {}
        for section, values in payload.items():
            if not isinstance(values, dict):
                continue
            result[str(section)] = {str(key): value for key, value in values.items()}
        return result

    # legacy env partial fallback
    pairs: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        pairs[key.strip()] = value
    return {"strategy": {key.lower().removeprefix("strategy_"): value for key, value in pairs.items()}}


def render_toml_value(value: object) -> str:
    """문자열 값을 TOML 표현으로 렌더링한다."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return str(value)
    lowered = value.strip().lower()
    if lowered in {"true", "false"}:
        return lowered
    try:
        int(value)
        return value.strip()
    except ValueError:
        pass
    try:
        float(value)
        return value.strip()
    except ValueError:
        pass
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def quote_toml_key(key: str) -> str:
    """TOML key 가 bare key 로 안전하지 않으면 quoted key 로 만든다."""
    if re.fullmatch(r"[A-Za-z0-9_-]+", key):
        return key
    escaped = key.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _write_table(lines: list[str], table_path: list[str], payload: dict[str, object]) -> None:
    """중첩 dict 를 TOML table 로 재귀 저장한다."""
    if table_path:
        lines.append(f"[{'.'.join(quote_toml_key(part) for part in table_path)}]")
    scalar_items: list[tuple[str, object]] = []
    nested_items: list[tuple[str, dict[str, object]]] = []
    for key, value in payload.items():
        if isinstance(value, dict):
            nested_items.append((key, value))
        else:
            scalar_items.append((key, value))
    for key, value in scalar_items:
        lines.append(f"{quote_toml_key(key)} = {render_toml_value(value)}")
    if scalar_items:
        lines.append("")
    for key, nested in nested_items:
        _write_table(lines, [*table_path, key], nested)


def write_runtime_local(path: Path, payload: dict[str, dict[str, object]]) -> None:
    """runtime.local.toml 파일을 저장한다."""
    lines = [
        "# Auto Coin Bot runtime local override",
        "# generated by tools/apply_strategy_set.py",
        "",
    ]
    for section in sorted(payload):
        section_payload = payload[section]
        if not isinstance(section_payload, dict):
            continue
        _write_table(lines, [section], section_payload)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def collect_changed_keys(payload: dict[str, dict[str, object]]) -> list[str]:
    """section.key 형식으로 변경 목록을 만든다."""
    changed: list[str] = []
    def visit(prefix: list[str], value: object) -> None:
        if isinstance(value, dict):
            for key in sorted(value):
                visit([*prefix, key], value[key])
            return
        changed.append(".".join(prefix))
    for section in sorted(payload):
        visit([section], payload[section])
    return changed


def build_parser() -> argparse.ArgumentParser:
    """CLI 인자 파서를 만든다."""
    parser = argparse.ArgumentParser(description="TOML 전략 세트 적용 도구")
    parser.add_argument(
        "--set",
        required=True,
        help="세트 별칭(conservative|medium|mixed) 또는 TOML 파일 경로",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="실제 반영 없이 변경될 section.key 만 출력",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI 진입점."""
    args = build_parser().parse_args(argv)
    set_path = resolve_set_path(args.set)
    payload = parse_set_file(set_path)
    changed = collect_changed_keys(payload)
    mode_label = "미리보기" if args.dry_run else "적용 완료"
    print(f"{mode_label}: {set_path}")
    if not changed:
        print("- 변경될 key 없음")
        return 0
    for item in changed:
        print(f"- {item}")
    if not args.dry_run:
        write_runtime_local(TARGET_PATH, payload)
        print(f"- runtime local: {TARGET_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
